### ISSUE TITLE
TypeError: round(): Argument #1 ($num) must be of type int|float, string given in .../vendor/pixlee/magento2/Model/Cart.php:161

### ISSUE THREAD

**Issue by vchiriacmoldoweb** [pixlee/magento2#84]
Please fix this issue, on success page, on latest version.

**Comment by ptrollinspt** [comment]
@vchiriacmoldoweb this is fixed by [Release v3.0.0](https://github.com/pixlee/magento2/releases/tag/v3.0.0).
